name: Executar programa de temperatura cada dia

on:
  schedule:
    - cron: '59 23 * * *'  # Cada dia a les 23:59 UTC
  workflow_dispatch:       # Opcional: permet executar-ho manualment

jobs:
  execucio-temperatura:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositori
        uses: actions/checkout@v3

      - name: Instal·lar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instal·lar dependències
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Executar programa
        run: python el_teu_programa.py

