"""name: Executar programa de temperatura cada dia

on:
  schedule:
    - cron: '*/5 * * * *'  # 23:59 hora espanyola (UTC+2)
  workflow_dispatch:

jobs:
  execucio-temperatura:
    runs-on: ubuntu-latest
    
    # Configura els permisos per escriure al repositori
    permissions:
      contents: write  # Permet al workflow fer push

    steps:
      - name: Clonar el repositori
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Permet fer push

      - name: Instal·lar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instal·lar dependències
        run: |
          pip install requests

      - name: Executar el programa
        run: python meteo.py

      - name: Fer commit del fitxer .json
        run: |
          git config user.name "paunieto23"
          git config user.email "actions@github.com"
          git add temp_*.json
          git commit -m "Afegit fitxer de temperatura del dia" || echo "No hi ha canvis a commitejar"
          git push"""

